version: 2

jobs:
  gcc:
    docker:
      - image: outpostuniverse/circleci-gcc-clang-googletest-nuget:1.1
    steps:
      - checkout
      - run: git submodule update --init
      - run: make -k CXX=g++
  clang:
    docker:
      - image: outpostuniverse/circleci-gcc-clang-googletest-nuget:1.1
    steps:
      - checkout
      - run: git submodule update --init
      - run: make -k CXX=clang++

workflows:
  version: 2
  build:
    jobs:
      - gcc
      - clang
